version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - BUILDCONFIG: Debug
  - BUILDCONFIG: Release
build_script:
- cmd: dotnet build -c %BUILDCONFIG%
test_script:
- cmd: dotnet test -c %BUILDCONFIG% Hedgehog.Experimental.Tests
artifacts:
- path: '**\Release\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: G45OD3ASmPDb+WoYqJ+FXzd43FYCWakr6EO720xMk2FU3nm1NtfmcWKM3/a8dBGP
  on:
    appveyor_repo_tag: true